
Vagrant.configure("2") do |config|

  

  config.vm.define "cento01" do |cento01|
    cento01.vm.hostname = "srv1-centos"
    cento01.vm.network "private_network", ip: "192.168.0.44"
    cento01.vm.network "public_network"
    cento01.vm.box = "centos/7"
    cento01.vm.synced_folder ".", "/vagrant_data"
    cento01.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
     end
   end
end