Vagrant.configure("2") do |config|

  

  config.vm.define "ns1" do |ns1|
    ns1.vm.hostname = "ns1"
    ns1.vm.network "private_network", ip: "192.168.10.18"
    ns1.vm.box = "ubuntu/trusty64"
    ns1.vm.synced_folder ".", "/vagrant_data"
    ns1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end