
Vagrant.configure("2") do |config|

  

  config.vm.define "ubuntu02" do |ubuntu02|
    ubuntu02.vm.hostname = "ubuntu02"
    ubuntu02.vm.network "private_network", ip: "192.168.5.21"
    ubuntu02.vm.box = "ubuntu/xenial64"
    ubuntu02.vm.synced_folder ".", "/vagrant_data"
    ubuntu02.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end