
Vagrant.configure("2") do |config|

  

  config.vm.define "app01" do |app01|
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.10.12"
    app01.vm.network  "forwarded_port", guest: "8000", host: "8080"
    app01.vm.box = "ubuntu/xenial64"
    app01.vm.synced_folder ".", "/vagrant_data"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end