---

 - name: Install Apache2
   apt: name=apache2 state=latest force=yes update_cache=yes 
 - name: Create custom index.html
   copy: dest=/var/www/ content='Hi, I am {{ ansible_hostname }}'
 - name: set file stats on index.html
   file: path=/var/www/ owner=root group=root mode=0644
 - name: Start apache
   service: name=apache2 state=started