
Vagrant.configure("2") do |config|

  

  config.vm.define "srv1" do |srv1|
    srv1.vm.hostname = "ubuntu-c"
    srv1.vm.network "private_network", ip: "192.168.0.41"
    srv1.vm.network "public_network"
    srv1.vm.box = "ubuntu/trusty64"
    srv1.vm.synced_folder ".", "/vagrant_data"
    srv1.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
     end
   end
end
