Vagrant.configure("2") do |config|

  

  config.vm.define "srv4" do |srv4|
    srv4.vm.hostname = "ubuntu3"
    srv4.vm.network "private_network", ip: "192.168.0.44"
    srv4.vm.network "public_network"
    srv4.vm.box = "ubuntu/trusty64"
    srv4.vm.synced_folder ".", "/vagrant_data"
    srv4.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
     end
   end
end