
Vagrant.configure(2) do |config|
  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.2.10"
    controller.vm.box = "ubuntu/trusty64"
    controller.vm.synced_folder ".", "/vagrant_data" 
    controller.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
    controller.vm.provision "shell", inline: <<-SHELL
      sudo apt install software-properties-common -y
      sudo apt install vim
      sudo apt-add repository ppa:ansible/ansible -y
      sudo apt update
      sudo apt install ansible -y
    SHELL
  end
  config.vm.define "web01" do |web01|
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.4.20"
    web01.vm.box = "ubuntu/trusty64"
    web01.vm.synced_folder ".", "/vagrant_data"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end
