

Vagrant.configure("2") do |config|

  

  config.vm.define "lb01" do |lb01|
    lb01.vm.hostname = "lb01"
    lb01.vm.network "private_network", ip: "192.168.10.11"
    lb01.vm.box = "centos/7"
    lb01.vm.synced_folder ".", "/vagrant_data"
    lb01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end