---
- name: apache2 listen on port {insert port}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen {{http_port}}" state=present
  
- name: apache2 virtualhost on port {insert port} 
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:{{ http_port }}>" 
  notify:
    - restart apache2