
Vagrant.configure("2") do |config|

  

  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx"
    nginx.vm.network "private_network", ip: "192.168.7.20"
    nginx.vm.box = "ubuntu/xenial64"
    nginx.vm.synced_folder ".", "/vagrant_data"
    nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end