
Vagrant.configure("2") do |config|

  

  config.vm.define "centobox" do |nginx2|
    nginx2.vm.hostname = "centobox"
    nginx2.vm.network "private_network", ip: "192.168.7.21"
    nginx2.vm.box = "centos/7"
    nginx2.vm.synced_folder ".", "/vagrant_data"
    nginx2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end