
Vagrant.configure("2") do |config|

  

  config.vm.define "backups" do |backups|
    backups.vm.hostname = "backups"
    backups.vm.network "private_network", ip: "192.168.10.15"
    backups.vm.box = "ubuntu/trusty64"
    backups.vm.synced_folder ".", "/vagrant_data"
    backups.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end