Vagrant.configure("2") do |config|

  

  config.vm.define "srv3" do |srv3|
    srv3.vm.hostname = "srv3-ubuntu"
    srv3.vm.network "private_network", ip: "192.168.0.43"
    srv3.vm.network "public_network"
    srv3.vm.box = "ubuntu/trusty64"
    srv3.vm.synced_folder ".", "/vagrant_data"
    srv3.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
     end
   end
end