Vagrant.configure("2") do |config|

  

  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring"
    monitoring.vm.network "private_network", ip: "192.168.10.16"
    monitoring.vm.box = "ubuntu/trusty64"
    monitoring.vm.synced_folder ".", "/vagrant_data"
    monitoring.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end