
Vagrant.configure("2") do |config|

  

  config.vm.define "db1" do |db1|
    db1.vm.hostname = "db1"
    db1.vm.network "private_network", ip: "192.168.10.14"
    db1.vm.box = "ubuntu/trusty64"
    db1.vm.synced_folder ".", "/vagrant_data"
    db1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end