---

 - name: Launch instances
   gce:
       instance_names: "{{ instance_name }}"
       machine_type: "{{ machine_type }}"
       image: "{{ image }}"
       service_account_email: "{{ service_account_email }}"
       credentials_file: "{{ credentials_file }}"
       project_id: "{{ project_id }}"
       zone: "{{ zone }}"