
Vagrant.configure("2") do |config|

  

  config.vm.define "ubuntu01" do |ubuntu01|
    ubuntu01.vm.hostname = "ubuntu01"
    ubuntu01.vm.network "private_network", ip: "192.168.5.20"
    ubuntu01.vm.box = "ubuntu/xenial64"
    ubuntu01.vm.synced_folder ".", "/vagrant_data"
    ubuntu01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end
