
Vagrant.configure("2") do |config|

  

  config.vm.define "ubuntu03" do |ubuntu03|
    ubuntu03.vm.hostname = "ubuntu03"
    ubuntu03.vm.network "private_network", ip: "192.168.6.20"
    ubuntu03.vm.box = "ubuntu/xenial64"
    ubuntu03.vm.synced_folder ".", "/vagrant_data"
    ubuntu03.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end