
Vagrant.configure("2") do |config|

  

  config.vm.define "ubuntu04" do |ubuntu04|
    ubuntu04.vm.hostname = "ubuntu04"
    ubuntu04.vm.network "private_network", ip: "192.168.6.21"
    ubuntu04.vm.box = "ubuntu/xenial64"
    ubuntu04.vm.synced_folder ".", "/vagrant_data"
    ubuntu04.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end