
Vagrant.configure("2") do |config|

  

  config.vm.define "srv0" do |srv0|
    srv0.vm.hostname = "dnsmasq"
    srv0.vm.network "private_network", ip: "192.168.0.40"
    srv0.vm.network "public_network"
    srv0.vm.box = "ubuntu/trusty64"
    srv0.vm.synced_folder ".", "/vagrant_data"
    srv0.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
     end
   end
end