
Vagrant.configure("2") do |config|

  

  config.vm.define "app02" do |app02|
    app02.vm.hostname = "app02"
    app02.vm.network "private_network", ip: "192.168.10.13"
    app02.vm.box = "centos/7"
    app02.vm.synced_folder ".", "/vagrant_data"
    app02.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end