
Vagrant.configure("2") do |config|

  

  config.vm.define "cento01" do |cento01|
    cento01.vm.hostname = "cento01"
    cento01.vm.network "private_network", ip: "192.168.7.21"
    cento01.vm.box = "centos/7"
    cento01.vm.synced_folder ".", "/vagrant_data"
    cento01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end