---

#- name: Install PHP Dependencies
#  apt: name-{{item}} state=present
#  with_items:
#  - python-software-properties
#  - software-properties-common

#- name: Add Php Repo
#  raw: LC_ALL=en_us.UTF-8 add-apt-repository ppa:ondrej/php -y

- name: Update Apt Cache
  apt: update_cache=yes

- name: Install PHP 7.1
  apt: name=php7.1 state=present force=yes
  