
Vagrant.configure("2") do |config|

  

  config.vm.define "kube" do |kube|
    kube.vm.hostname = "cento01"
    kube.vm.network "private_network", ip: "192.168.20.10"
    kube.vm.box = "ubuntu/xenial64"
    kube.vm.synced_folder ".", "/vagrant_data"
    kube.vm.provider "virtualbox" do |vb|
      vb.memory = "2024"
     end
   end
end