
Vagrant.configure("2") do |config|

  

  config.vm.define "web02" do |web02|
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.5.21"
    web02.vm.box = "ubuntu/xenial64"
    web02.vm.synced_folder ".", "/vagrant_data"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
     end
   end
end